#include "CommandObject.h"
#include <iostream>
#include <string>
using namespace std;

int CommandObject::help()
{
	string str;

	cout<<"==============命令详解：图层管理命令=============="<<endl;
	cout<<"create filename"<<endl;
	cout<<"  用途：新建图层，并载入文件名为filename的图像，执行后，新图层被选中"<<endl;
	cout<<"  参数：char* filename；仅限当前目录的bmp图像文件；"<<endl;
	cout<<"  示例：create temp.bmp"<<endl;
	cout<<""<<endl;
	cout<<"delete"<<endl;
	cout<<"  用途：删除当前选中图层"<<endl;
	cout<<""<<endl;
	cout<<"delete layername"<<endl;
	cout<<"  用途：删除名称为layername的图层"<<endl;
	cout<<"  参数：layername图层名称，可通过info命令查看"<<endl;
	cout<<"  示例：delete L0"<<endl;
	cout<<""<<endl;
	cout<<"duplicate"<<endl;
	cout<<"  用途：复制当前图层，执行后，新图层位于最顶上，且被选中"<<endl;
	cout<<""<<endl;
	cout<<"info"<<endl;
	cout<<"  用途：给出当前文档信息，包括画布大小，当前选中图层，每层信息"<<endl;
	cout<<""<<endl;
	cout<<"select layername"<<endl;
	cout<<"  用途：选中名称为layername的图层"<<endl;
	cout<<"  参数：layername图层名称，可通过info命令查看"<<endl;
	cout<<"  示例：select L0"<<endl;
	cout<<""<<endl;
	cout<<"setsize width height"<<endl;
	cout<<"  用途：将画布调整为宽width像素，高height像素。调整后，原有图像都在新画布左上角"<<endl;
	cout<<"  参数：int width,height；建议两者值均小于1000"<<endl;
	cout<<"  示例：setsize 800 600"<<endl;
	cout<<""<<endl;
	cout<<"……按任意键继续…… "<<endl;
	getline(cin,str);
	cout<<"==============命令详解：图层调整命令=============="<<endl;
	cout<<"moveto x y"<<endl;
	cout<<"  用途：将选中图层移到相对画布（x，y）位置"<<endl;
	cout<<"  参数：int x，y;坐标原点（0，0）位于左上角，x>0代表在原点右方，y>0代表在原点下方"<<endl;
	cout<<"  示例：moveto 20 15"<<endl;
	cout<<""<<endl;
	cout<<"mixmode mode"<<endl;
	cout<<"  用途：设置选中图层的混合模式"<<endl;
	cout<<"  参数：int mode的值可以为"<<endl;
	cout<<"            0 覆盖"<<endl;
	cout<<"            1 变暗（以上下层中较暗的颜色为混合色）"<<endl;
	cout<<"            2 变亮（以上下层中较亮的颜色为混合色）"<<endl;
	cout<<"            注意，当mode不为0时，不透明度属性失效"<<endl;
	cout<<"  示例：mixmode 1"<<endl;
	cout<<""<<endl;
	cout<<"setname name"<<endl;
	cout<<"  用途：将选中图层的名称改为name"<<endl;
	cout<<"  参数：char* name"<<endl;
	cout<<"  示例：setname myL"<<endl;
	cout<<""<<endl;
	cout<<"setz mode"<<endl;
	cout<<"  用途：将选中图层向上或向下移动"<<endl;
	cout<<"  参数：char* mode的值可以为"<<endl;
	cout<<"            top         当前层置顶"<<endl;
	cout<<"            bottom  当前层置底"<<endl;
	cout<<"            up          当前层向上移一层"<<endl;
	cout<<"            down     当前层向下移一层"<<endl;
	cout<<"  示例：setz top"<<endl;
	cout<<""<<endl;
	cout<<"transparency trp"<<endl;
	cout<<"  用途：设置选中图层的透明度"<<endl;
	cout<<"  参数：int trp；trp范围为0~100；注意，当mode不为0时，不透明度属性失效"<<endl;
	cout<<"  示例：transparency 10"<<endl;
	cout<<""<<endl;
	cout<<"……按任意键继续…… "<<endl;
	getline(cin,str);
	cout<<"==============命令详解：图像调整命令=============="<<endl;
	cout<<"rotate angle"<<endl;
	cout<<"  用途：逆时针旋转angle度当前选中图层的图像"<<endl;
	cout<<"  参数：double angle；"<<endl;
	cout<<"  示例：rotate 45"<<endl;
	cout<<""<<endl;
	cout<<"zoom width height"<<endl;
	cout<<"  用途：将选中图层的图像调整至宽为width像素，高为height像素的图像"<<endl;
	cout<<"  参数：int width;int height;建议width和height值不大于1000；"<<endl;
	cout<<"  示例：zoom 800 600"<<endl;
	cout<<""<<endl;
	cout<<"zoom zoomx zoomy"<<endl;
	cout<<"  用途：将选中图层的图像的宽放大（缩小）至画布宽的zoomx%，高放大（缩小）至画布长的"<<endl;
	cout<<""<<endl;
	cout<<"zoomy%"<<endl;
	cout<<"  参数：zoomx，zoomy为字符串形，表示法为0%至100%"<<endl;
	cout<<"  示例：zoom 200% 200%"<<endl;
	cout<<""<<endl;
	cout<<"setblank red green blue tolerance"<<endl;
	cout<<"  用途：对于选中图层的图像，将颜色为以（red，green，blue）为基准的，容差为tolerance"<<endl;
	cout<<""<<endl;
	cout<<"的颜色设为透明"<<endl;
	cout<<"  参数：red，green，blue范围为0~255；tolerance建议设为10，一般小于32；"<<endl;
	cout<<"  示例：setblank 255 255 255 10 （将白色设为透明色）"<<endl;
	cout<<""<<endl;
	cout<<"histogram [mode]"<<endl;
	cout<<"  用途：给出当前图像的直方图"<<endl;
	cout<<"  参数：mode的值可以为"<<endl;
	cout<<"            1 R通道"<<endl;
	cout<<"            2 G通道"<<endl;
	cout<<"            3 B通道"<<endl;
	cout<<"            4 所有颜色通道"<<endl;
	cout<<"            5 RGB通道"<<endl;
	cout<<"            如果mode未给出，则默认为5"<<endl;
	cout<<"  示例：histogram 5"<<endl;
	cout<<" "<<endl;
	cout<<"……按任意键继续…… "<<endl;
	getline(cin,str);
	cout<<"==============命令详解：程序命令=============="<<endl;
	cout<<"exit"<<endl;
	cout<<"  用途：退出程序"<<endl;
	cout<<""<<endl;
	cout<<"help"<<endl;
	cout<<"  用途：获得帮助"<<endl;
	cout<<""<<endl;
	cout<<"save"<<endl;
	cout<<"  用途：保存当前修改结果至temp.bmp"<<endl;
	cout<<""<<endl;
	cout<<"save filename"<<endl;
	cout<<"  用途：保存当前修改结果至名称为filename的文件"<<endl;
	cout<<"  参数：char* filename；bmp图像文件名；"<<endl;
	cout<<"  示例：save out.bmp"<<endl;
	cout<<""<<endl;
	cout<<"show"<<endl;
	cout<<"  用途：调用外部程序，显示当前修改后的图像"<<endl;

	return 1;
}